---
# Copyright (c) 2018, Oracle and/or its affiliates.
# This software is made available to you under the terms of the GPL 3.0 license or the Apache 2.0 license.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Apache License v2.0
# See LICENSE.TXT for details.

- name : List all compute instances in Ansible compartment
  connection: local
  hosts: localhost
  tasks:
    - name: Create bucket
      oci_instance_facts:
        # pick the compartment_id from the environment variable SAMPLE_COMPARTMENT_OCID
        compartment_id: "{{ lookup('env', 'SAMPLE_COMPARTMENT_OCID') }}"         
      register: currinstances
    - debug:
        msg: "{{currinstances}}"

