---
# Copyright (c) 2018, Oracle and/or its affiliates.
# This software is made available to you under the terms of the GPL 3.0 license or the Apache 2.0 license.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Apache License v2.0
# See LICENSE.TXT for details.

#Task for creating private subnet for ad2

- name: Create private subnet for AD2
  oci_subnet:
    display_name: "{{ private_subnet_ad2_name }}"
    availability_domain: "{{ availability_domain_2 }}"
    cidr_block: "{{ cidr_block_private_ad2 }}"
    compartment_id: "{{ compartment_id }}"
    prohibit_public_ip_on_vnic: true
    vcn_id: "{{ demo_vcn_ocid }}"
    dns_label: "{{ dns_label_ad2 }}"
    security_list_ids: ["{{ private_sec_list_ad2_id }}"]
    route_table_id: "{{ private_subnet_ad2_rt_id }}"
  register: result

- set_fact:
   private_subnet_ad2_id: "{{ result.subnet.id }}"
   private_subnet_ad2_dns_label: "{{ result.subnet.dns_label }}"   
